apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: cloudtrace-agent
  namespace: prj-bych-gke-lab001
  annotations:
    config.kubernetes.io/depends-on: iam.cnrm.cloud.google.com/namespaces/prj-bych-gke-lab001/IAMServiceAccount/gke-primary-pool
spec:
  memberFrom:
    serviceAccountRef:
      name: gke-primary-pool
      namespace: prj-bych-gke-lab001
  resourceRef:
    kind: Project
    external: prj-bych-gke-lab001
  role: roles/cloudtrace.agent
