apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeatureMembership
metadata:
  name: gke-acm-membership
  namespace: prj-bych-gke-lab001
  annotations:
    config.kubernetes.io/depends-on: gkehub.cnrm.cloud.google.com/namespaces/prj-bych-gke-lab001/GKEHubMembership/gke,gkehub.cnrm.cloud.google.com/namespaces/prj-bych-gke-lab001/GKEHubFeature/configmanagement
spec:
  projectRef:
    external: prj-bych-gke-lab001
  location: global
  membershipRef:
    name: gke
  featureRef:
    name: configmanagement
  configmanagement:
    configSync:
      sourceFormat: unstructured
      git:
        policyDir: .
        secretType: none
        syncBranch: main
        syncRepo: https://github.com/mbychkowski/gcp-acm-workshop-gke-configs
    policyController:
      enabled: true
      referentialRulesEnabled: true
      logDeniesEnabled: true
      templateLibraryInstalled: true
    version: "1.13.0"
