apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouter
metadata:
  name: gke
  namespace: prj-bych-gke-lab001
  annotations:
    config.kubernetes.io/depends-on: compute.cnrm.cloud.google.com/namespaces/prj-bych-gke-lab001/ComputeNetwork/gke
spec:
  networkRef:
    name: gke
  region: northamerica-northeast1
