apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: containercluster-sample-autopilot
  namespace: ${TENANT_PROJECT_ID}
spec:
  description: An autopilot cluster.
  enableAutopilot: true
  location: us-west1
  releaseChannel:
    channel: REGULAR