apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: containercluster-sample-autopilot
  namespace: qwiklabs-gcp-01-613722232c89
spec:
  description: An autopilot cluster.
  enableAutopilot: true
  location: us-west1
  releaseChannel:
    channel: REGULAR