apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: "abandon"
    cnrm.cloud.google.com/disable-dependent-services: "false"
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/config-control/Project/qwiklabs-gcp-00-13ac835469c2
  name: qwiklabs-gcp-00-13ac835469c2-compute
  namespace: config-control
spec:
  projectRef:
    name: qwiklabs-gcp-00-13ac835469c2
  resourceID: compute.googleapis.com
