# apiVersion: core.cnrm.cloud.google.com/v1beta1
# kind: ConfigConnectorContext
# metadata:
#   name: configconnectorcontext.core.cnrm.cloud.google.com
#   namespace: qwiklabs-gcp-00-13ac835469c2
#   annotations:
#     config.kubernetes.io/depends-on: iam.cnrm.cloud.google.com/namespaces/config-control/IAMServiceAccount/qwiklabs-gcp-00-13ac835469c2
# spec:
#   googleServiceAccount: qwiklabs-gcp-00-13ac835469c2@qwiklabs-gcp-00-13ac835469c2.iam.gserviceaccount.com