apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeatureMembership
metadata:
  name: gke-acm-demo-cluster-acm-membership
  namespace: qwiklabs-gcp-04-24351b679a98
  annotations:
    config.kubernetes.io/depends-on: gkehub.cnrm.cloud.google.com/namespaces/qwiklabs-gcp-04-24351b679a98/GKEHubMembership/gke-acm-demo-cluster,gkehub.cnrm.cloud.google.com/namespaces/qwiklabs-gcp-04-24351b679a98/GKEHubFeature/configmanagement
spec:
  projectRef:
    external: qwiklabs-gcp-04-24351b679a98
  location: global
  membershipRef:
    name: gke-acm-demo-cluster
  featureRef:
    name: configmanagement
  configmanagement:
    configSync:
      sourceFormat: unstructured
      git:
        policyDir: .
        secretType: none
        syncBranch: main
        syncRepo: https://github.com/mbychkowski/gcp-acm-workshop-gke-configs
    policyController:
      enabled: true
      referentialRulesEnabled: true
      logDeniesEnabled: true
      templateLibraryInstalled: true
    version: "1.13.0"
